### ISSUE TITLE
10-minute lockout when confirming a reservation

### ISSUE THREAD

**Issue by vaniabudiman** [UBC-CPSC319/team-12#14]
Once a user has indicated they want to book a specific desk they will be provided with confirmation workflow if that desk is available. In this confirmation workflow, the desk will be restricted from being booked by other users. This restriction will last for a maximum of 10 minutes

**Comment by vaniabudiman** [comment]
Suggestion - 10 min lockdown: 5 second buffer before sending out the request. That way, you won’t overload the server

**Comment by holybom** [comment]
[](/home/ec2-user/team-12/server/config/config.json)
