### ISSUE TITLE
System will archive expired bookings

### ISSUE THREAD

**Issue by vaniabudiman** [UBC-CPSC319/team-12#27]
"A DBA script to offload non-active bookings into an ‘archive’ table would be needed to
maintain high system performance." - HSBC-provided document

**Comment by steventce** [comment]
The DBA script will create an event in mysql that will remove all expired reservations every midnight. Refer to the README for instructions on how to setup the event.

c8ac4e212441241cc23e317f078aac7de236d124
88a20383646eb3b8eed5aaf286065cd4b880dbd8
