### ISSUE TITLE
Fix tab issue on the header navbar

### ISSUE THREAD

**Issue by vaniabudiman** [UBC-CPSC319/team-12#44]
Should not be stuck on "Admin reservations"

**Comment by willyao94** [comment]
see themeteorchef's post in https://github.com/react-bootstrap/react-router-bootstrap/issues/152

**Comment by eflem00** [comment]
The above lead me to https://github.com/reactjs/react-redux/blob/master/docs/troubleshooting.md which fixed the issue by setting the connection to "pure: false"

**Comment by vaniabudiman** [comment]
This doesn't looked like it's fixed? I tested on dev branch and on mylasagna.ca

**Comment by vaniabudiman** [comment]
Nevermind, I guess we are developing on master branch now
