### ISSUE TITLE
CSV export datetimes bug

### ISSUE THREAD

**Issue by vaniabudiman** [UBC-CPSC319/team-12#49]
"When I try to export to CSV.   It mechanically exports correctly.   In fact, the errors noted in (h) above show correctly in the CSV file??!!  (ie: it shows 2pm to 10pm!).	Screen shot of CSV file inside Excel below.   Not sure of the meaning of ‘Z’ in the date/time fields."

https://piazza.com/class/ivy30yphlhg3ok?cid=531

**Comment by vaniabudiman** [comment]
If time allows, we should also remove "cancel" and "edit" columns since those are irrelevant

**Comment by kingeric0201** [comment]
56e53c8fb115fa856c0a73925f2ec4fd884b68f5
