### ISSUE TITLE
Cancel/delete button

### ISSUE THREAD

**Issue by vaniabudiman** [UBC-CPSC319/team-12#50]
According to Julin, it does not work. But also we should also change the label from Cancel --> Delete

https://piazza.com/class/ivy30yphlhg3ok?cid=546

**Comment by steventce** [comment]
There is a foreign key constrain in the production database that does not allow for cascading delete of reservations if the resource is deleted.

I've moved the process of creating the initial database schema via Sequelize migration. The migration needs to be applied to mylasagna.ca. Instructions are in the Readme. Please install the Sequelize command line interface (npm install in server) and run the migration command.

https://github.com/sequelize/cli

**Comment by steventce** [comment]
The label has already been changed from Cancel to Delete.

**Comment by holybom** [comment]
@steventce Any work left for this?

**Comment by steventce** [comment]
Working properly on mylasagna.ca. Closing.
