### ISSUE TITLE
Padding between Time Remaining countdown and Cancel/OK buttons in modal

### ISSUE THREAD

**Issue by vaniabudiman** [UBC-CPSC319/team-12#55]
Styling issue

**Comment by holybom** [comment]
how much padding?

**Comment by vaniabudiman** [comment]
Could be 25px or you could pull it all the way to the left - either works

**Comment by holybom** [comment]
{649476d0}(https://github.com/UBC-CPSC319/team-12/commit/649476d0fc99fedd348a26db7fe067d63c185281)
