### ISSUE TITLE
Resource can be edited to be booked twice in Admin Reservations

### ISSUE THREAD

**Issue by steventce** [UBC-CPSC319/team-12#63]
**Steps to Reproduce:**
1. Make several reservations
2. Edit the reservations so that the start and end date times are within each other

**Expected Result:**
An error message to indicate that the resource has been booked already

**Comment by vaniabudiman** [comment]
"The administration allows for editing of a booking that encroaches another booking. For instance, I had 2 bookings.   Booking 1 was for desk 1.A.101 Apr 30 1am to Apr 30 11pm,   Booking 2 was desk 1.A.101 May 1 1am to May 1 11pm.   I changed the first booking as administrator to extend booking to May 1 4pm and it allowed me.   Therefore there are two people booked for desk 1.A.101 for May 1."

Source:
https://piazza.com/class/ivy30yphlhg3ok?cid=606

**Comment by vaniabudiman** [comment]
I think I may have fixed it. I am going to leave this issue open so someone else can verify that this is actually fixed.

Feel free to revert/change the following commit as you please.

commit ecc9357b6718f2c4e9d2dd7c1bbaef1938ee6dbd
Author: Vania Budiman <evaniab@msn.com>
Date:   Sun Apr 16 00:23:28 2017 -0700

    Admin: editing reservations should deny the user of having overlapping times for the same resource

**Comment by vaniabudiman** [comment]
commit b0c7e81ffe1c6f74efb7384556303ae0b558cd78
Author: Vania Budiman <evaniab@msn.com>
Date:   Sun Apr 16 20:30:28 2017 -0700

    Edit reservation: start/end times should never be the same
