### ISSUE TITLE
Update UI after 10 minutes

### ISSUE THREAD

**Issue by vaniabudiman** [UBC-CPSC319/team-12#65]
"After the 10 minute countdown, nothing happens and the cancel or ok button still here. When I click the ok button then the message indicating booking has expired occurs."

Source:
https://piazza.com/class/ivy30yphlhg3ok?cid=606

I think they are looking for some kind of UI update after 10 minutes - up to you however you want to show it to the user

**Comment by holybom** [comment]
The OK button is now disabled when timer expires, and the time remaining becomes a red "TIMED OUT!" message.

**Comment by vaniabudiman** [comment]
Tested & works. Nice job Tam :)
