### ISSUE TITLE
Multiple user login

### ISSUE THREAD

**Issue by vaniabudiman** [UBC-CPSC319/team-12#73]
"Your system does not allow us to multiple login as different users. So there are certain functions we cannot test.   Can you provide multiple user access?"

"Part of separate users, we cannot see if admin functions co-mingle with standard user functions."

Source:
https://piazza.com/class/ivy30yphlhg3ok?cid=606

**Comment by holybom** [comment]
[d7018](https://github.com/UBC-CPSC319/team-12/commit/d70180e3b8edf5cf3ae00e2530edd31b51fe3c0a)

Just a simple README instruction. @vaniabudiman I also added it to the [Installation Documentation...](https://docs.google.com/document/d/1Sctuv5zl4ucHx0O8uyYaPfpXlyWD4pbQobzoyu6Dafs/edit#)

**Comment by vaniabudiman** [comment]
I wonder if the best way is just to change the employee ID if they want to test admin vs. non-admin functionality. Probably not the most "elegant" way to test but whatever works at this point.
