### ISSUE TITLE
Hide resource from available resources list when resource is booked

### ISSUE THREAD

**Issue by vaniabudiman** [UBC-CPSC319/team-12#76]
"It would be a nice feature to have desk not appear on the pick list when they are not available (ie: booked)."

Source:
https://piazza.com/class/ivy30yphlhg3ok?cid=606

**Comment by steventce** [comment]
I believe this is implemented already on the list of available resources on the request page. I'll reply to Julin's post to see if she has a specific example.

**Comment by vaniabudiman** [comment]
Filtering works for when you have a reservation at 6pm and it is currently after 6pm right now - say, 6:15. It filters the list correctly.

But let's say it's 6:15 right now and you reserve 1.A.101 starting 9pm. Then you go back to the Request page and select 9pm as the time. Desk 1.A.101 still shows up on the Available Resources list.
