### ISSUE TITLE
10 min lockout: Closing confirmation and then starting timeout

### ISSUE THREAD

**Issue by vaniabudiman** [UBC-CPSC319/team-12#77]
"High priority: While letting confirmation time run out, somewhere at 4 minutes remaining - I wasn't looking at the page, an error popped up

It may have to do with me closing the confirmation box, then starting to timeout for the same resource again."

Source:
https://piazza.com/class/ivy30yphlhg3ok?cid=606

**Comment by holybom** [comment]
[dd1d3](https://github.com/UBC-CPSC319/team-12/commit/dd1d3d43924b75a4f9904de1b9a308c9aa38b558)

@vaniabudiman I had to update the [Technical Requirements & Internal Design v0.7](https://docs.google.com/document/d/1d5_x3cQAACZp9O3zRi02OcR-xYirUBoy2B4v4U5mCsI/edit) doc in the API section.
