### ISSUE TITLE
Resource Management by Location

### ISSUE THREAD

**Issue by vaniabudiman** [UBC-CPSC319/team-12#82]
1. Filtering locations by location_id
Beside the "Add Resource" button, there should be a dropdown in which the user can select a location. When the user selects a location, it filters the resources list to show only the resources in that location.

2. Add Resource
When you add a new resource, it adds a new resource to the currently selected location (the location that is currently filtering the resources table).

3. Edit Resource
When you edit a resource, it edits the resource without changing location information.

No changes to the add/edit resource location modals are required.

**Comment by steventce** [comment]
Commit: be3e0046ce8fd551c31905be71ef491c74c052ec

**Comment by vaniabudiman** [comment]
Verified that this works on localhost.
